#!/usr/bin/env python3
"""Generate the work-assignment ledger over the whole catalog.

Each module record is classified by TIER:
  - deep    : has >=1 code-read behavioral note (agent-reviewed) -> DONE
  - baseline: category-inferred only (sweep/gen_thin) -> TODO (needs agent review)

Outputs:
  - assignments.tsv : module | tier | status | value_model | apqc | models | routes | priority
  - ASSIGNMENTS.md  : summary + the prioritized TODO list (baseline records with the
                      most models/routes = highest-value agent upgrades).

priority = models*2 + routes (a rough "how much substance to review" score).
"""
import glob, json, os
from collections import Counter

ROOT = os.path.dirname(os.path.abspath(__file__))


def tier(rec):
    name = rec.get("subsystem", "")
    if name.startswith("test_") or name.startswith("l10n_test"):
        return "test"
    notes = rec.get("evidence", {}).get("behavioral_notes", [])
    return "deep" if any(n.get("source") == "code-read" for n in notes) else "baseline"


rows = []
for f in sorted(glob.glob(os.path.join(ROOT, "metamodel", "*.metamodel.json"))):
    r = json.load(open(f))
    ev = r["evidence"]
    nm = len(ev.get("models", []))
    nr = len(ev.get("routes", []))
    t = tier(r)
    rows.append({
        "module": r["subsystem"], "tier": t,
        "status": "done" if t == "deep" else "todo",
        "value_model": r["classification"]["value_model"],
        "apqc": (r["classification"].get("apqc_category") or "?").split(" ")[0],
        "models": nm, "routes": nr, "priority": nm * 2 + nr,
    })

# TSV
with open(os.path.join(ROOT, "assignments.tsv"), "w") as out:
    out.write("module\ttier\tstatus\tvalue_model\tapqc\tmodels\troutes\tpriority\n")
    for r in sorted(rows, key=lambda r: (-r["priority"], r["module"])):
        out.write("\t".join(str(r[k]) for k in
                  ("module", "tier", "status", "value_model", "apqc", "models", "routes", "priority")) + "\n")

deep = [r for r in rows if r["tier"] == "deep"]
base = [r for r in rows if r["tier"] == "baseline"]
test = [r for r in rows if r["tier"] == "test"]
# prioritize real business modules: exclude localizations from the upgrade queue
biz_todo = [r for r in base if not r["module"].startswith("l10n_")]
top_todo = sorted(biz_todo, key=lambda r: -r["priority"])[:40]
l10n_n = sum(1 for r in base if r["module"].startswith("l10n_"))

md = []
md.append("# revres Work Assignments Ledger\n")
md.append(f"> Coverage and to-do across **{len(rows)} modules**. "
          f"**{len(deep)} deep** (agent-reviewed, code-read behavior) · "
          f"**{len(base)} baseline** (category-inferred, awaiting agent upgrade). "
          "Full table in `assignments.tsv`.\n")
md.append("## Status summary\n")
md.append(f"- Total catalog: **{len(rows)}** modules (every installable module has a record).")
md.append(f"- **Deep** (agent-reviewed, DONE): **{len(deep)}**")
md.append(f"- **Baseline** (auto-classified): **{len(base)}** "
          f"(of which {l10n_n} are `l10n_*` localizations — keep baseline)")
md.append(f"- **Test** fixtures (excluded from review): **{len(test)}**")
vmc = Counter(r["value_model"] for r in rows)
md.append(f"- Value models: " + ", ".join(f"{k}={v}" for k, v in sorted(vmc.items())) + "\n")

md.append("## Assignment rule\n")
md.append("- **Deep tier** = the code-explorer+code-architect agent workflow "
          "(`AGENT_WORKFLOW.md`): real code-read behavioral notes, verified names.\n"
          "- **Baseline tier** = auto-classified sweep (`sweep_all.py` + `auto_classify.py`): "
          "structural facts + frontend + category-inferred value model. Correct shape, "
          "shallow classification.\n"
          "- **To upgrade a baseline -> deep:** run an agent per `AGENT_WORKFLOW.md` on it "
          "(overwrites the baseline record). Prioritize by the `priority` column "
          "(models*2 + routes).\n")

md.append("## Top 40 TODO (highest-substance baselines to upgrade next)\n")
md.append("| Module | Value | APQC | Models | Routes | Priority |")
md.append("|--------|-------|------|-------:|-------:|---------:|")
for r in top_todo:
    md.append(f"| {r['module']} | {r['value_model']} | {r['apqc']} | "
              f"{r['models']} | {r['routes']} | {r['priority']} |")

md.append(f"\n*Generated by assignments.py. {len(rows)} modules, {len(deep)} deep / {len(base)} baseline.*\n")
open(os.path.join(ROOT, "ASSIGNMENTS.md"), "w").write("\n".join(md) + "\n")
print(f"assignments: {len(rows)} modules | deep={len(deep)} baseline={len(base)}")
print("top TODO:", ", ".join(r["module"] for r in top_todo[:12]))
