#!/usr/bin/env python3
"""Consolidate all metamodel records into a rollup: a TSV catalog + a Markdown
summary (value-model x APQC x layer coverage). The Fit-to-Standard "Standard"
reference index over the whole catalog.

Usage: python3 doc/revres/rollup.py   ->  writes rollup.tsv + ROLLUP.md
"""
import glob, json, os
from collections import Counter, defaultdict

ROOT = os.path.dirname(__file__)
recs = []
for f in sorted(glob.glob(os.path.join(ROOT, "metamodel", "*.metamodel.json"))):
    recs.append(json.load(open(f)))


def layers(ev):
    L = ["meta"]
    if any(n.get("source") == "code-read" for n in ev.get("behavioral_notes", [])):
        L.append("code")
    if ev.get("frontend", {}).get("js_files"):
        L.append("fe")
    if ev.get("integrations", {}).get("http_call_sites") or ev.get("integrations", {}).get("sdk_imports"):
        L.append("integ")
    if ev.get("runtime", {}).get("models_with_data"):
        L.append("run")
    return L


# --- TSV ---
tsv = ["module\tvalue_model\tactivity\tapqc\tmodels\troutes\tjs\towl\tlayers"]
for r in recs:
    ev = r["evidence"]
    fe = ev.get("frontend", {})
    tsv.append("\t".join(str(x) for x in [
        r["subsystem"], r["classification"]["value_model"], r["classification"]["activity_class"],
        (r["classification"].get("apqc_category") or "?")[:28],
        len(ev.get("models", [])), len(ev.get("routes", [])),
        fe.get("js_files", 0), len(fe.get("owl_components", [])),
        "+".join(layers(ev))]))
open(os.path.join(ROOT, "rollup.tsv"), "w").write("\n".join(tsv) + "\n")

# --- aggregates ---
vm = Counter(r["classification"]["value_model"] for r in recs)
ac = Counter(r["classification"]["activity_class"] for r in recs)
apqc = Counter((r["classification"].get("apqc_category") or "?").split(" ")[0] for r in recs)
by_vm = defaultdict(list)
for r in recs:
    by_vm[r["classification"]["value_model"]].append(r["subsystem"])
layer_cov = Counter()
for r in recs:
    for L in layers(r["evidence"]):
        layer_cov[L] += 1

md = []
md.append("# revres Catalog Rollup — the Fit-to-Standard Standard Reference\n")
md.append(f"> Consolidated view of **{len(recs)} Odoo subsystem metamodel records** "
          "(generated by the code-explorer/code-architect workflow). Machine-readable "
          "table in `rollup.tsv`.\n")
md.append("## 1. Value-model distribution (Stabell & Fjeldstad)\n")
md.append("| Value model | Count | Modules |")
md.append("|-------------|------:|---------|")
for k in ("chain", "shop", "network", "support"):
    if by_vm.get(k):
        md.append(f"| {k} | {vm[k]} | {', '.join(sorted(by_vm[k]))} |")
md.append(f"\nActivity class: " + ", ".join(f"{k}={v}" for k, v in ac.items()) + "\n")

md.append("## 2. APQC PCF category coverage\n")
md.append("| APQC | Records |")
md.append("|------|--------:|")
for k in sorted(apqc, key=lambda x: (x == "?", x)):
    md.append(f"| {k} | {apqc[k]} |")

md.append("\n## 3. Reverse-engineering layer coverage\n")
md.append("| Layer | Records with it |")
md.append("|-------|----------------:|")
names = {"meta": "metadata (facts)", "code": "code-read (behavior)", "fe": "frontend (OWL/JS)",
         "integ": "integrations (HTTP/SDK)", "run": "runtime (live data)"}
for k in ("meta", "code", "fe", "integ", "run"):
    md.append(f"| {names[k]} | {layer_cov[k]}/{len(recs)} |")

md.append("\n## 4. Full catalog\n")
md.append("| Module | Value | Activity | APQC | Models | JS | Layers |")
md.append("|--------|-------|----------|------|-------:|---:|--------|")
for r in sorted(recs, key=lambda r: (r["classification"]["value_model"], r["subsystem"])):
    ev = r["evidence"]
    md.append(f"| {r['subsystem']} | {r['classification']['value_model']} | "
              f"{r['classification']['activity_class']} | "
              f"{(r['classification'].get('apqc_category') or '?')[:22]} | "
              f"{len(ev.get('models',[]))} | {ev.get('frontend',{}).get('js_files',0)} | "
              f"{'+'.join(layers(ev))} |")

md.append("\n## 5. How to use (Fit-to-Standard)\n")
md.append("- **chain** modules = the Make/Deliver standard flows; **shop** = service "
          "delivery; **network** = mediation/storefront; **support** = the shared "
          "infrastructure every workshop assumes.\n"
          "- For each customer requirement: find the covering module here -> read its "
          "`out/<module>.md` brief + `metamodel/<module>.metamodel.json` -> demo live via "
          "the `run-odoo` skill -> decide **Fit** (standard) or **Gap** (configure/dev).\n"
          "- `apqc` column maps each module to the customer's process taxonomy; "
          "`apqc_odoo_map.tsv` drills to activity-level (action_*).\n")
md.append(f"\n*Generated by rollup.py over doc/revres/metamodel/*.json. {len(recs)} records. Odoo 19.0.*\n")
open(os.path.join(ROOT, "ROLLUP.md"), "w").write("\n".join(md) + "\n")

print(f"rollup: {len(recs)} records -> rollup.tsv + ROLLUP.md")
print("value models:", dict(vm))
print("layer coverage:", dict(layer_cov))
